services:

  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    ports:
      - "3002:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/production/web
      - .env/production/database
    depends_on:
      - database
      - redis

  redis:
    image: redis

  database:
    image: mysql
    restart: always
    env_file:
      - .env/production/database
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/sql-data
    ports:
      - "3306:3306"

volumes:
  db_data:
